### ISSUE TITLE
keptn apply

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/enhancement-proposals#63]
# keptn apply

Introduce a `keptn apply` command which mirrors `kubectl apply` for a GitOps approach

## Motivation

* Extend Keptn GitOps approach

## Explanation

`keptn apply project.yaml` where project.yaml contains the project name + shipyard definition.

For example:

```
---
name: "my-first-project"
spec:
  shipyard:
    stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "task-here"
  services:
    - name: "service1"
    - name: "service2"
```
