### ISSUE TITLE
Independent Sequences

### ISSUE THREAD

**Issue by agardnerIT** [keptn/enhancement-proposals#79]
# Independent Sequences

Sequences within a project should be independent of one another. They should be able run concurrently or "out of order".

In other words, a queued sequence (for the future) should not block other "instant run" sequences.

## Motivation

Given a shipyard like this:

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "release-validation-shipyard"
spec:
  stages:
    - name: "validaterelease"
      sequences:
        - name: "runvalidation"
          tasks:
            - name: "evaluation"
              triggeredAfter: "60m"
              properties:
                timeframe: "2m"
```

If I request an execution of `runvalidation` I cannot process any other sequences in this project for the next 60 minutes. In effect, everything is queued behind that sequence and until that one sequence runs, my project is "locked".
