### ISSUE TITLE
Shipyard Enhancement: Include Services

### ISSUE THREAD

**Issue by agardnerIT** [keptn/enhancement-proposals#83]
Shipyard Enhancement: Include Services

Include service definitions in shipyard file

## Motivation

* Config as code and self contained
* Implementation of this means Keptn CLI could implement a `keptn init` command more easily.
* Project onboarding is easier: `keptn create project` creates project, stages and also services.

## Explanation

The Keptn shipyard file already contains a partial definition of a project, all stages of a project, all sequences within those stages and tasks. However it doesn't include the service definitions. This enhancement would see a shipyard file also include the service definitions.

## Internal details

For example:

```
apiVersion: "spec.keptn.sh/*.*.*"
kind: "Shipyard"
metadata:
  name: "shipyard"
spec:
  services:
    - name: "microserviceA"
    - name: "microserviceB"
    - ....
  stages:
    - name: "demo"
      sequences:
        - name: "hello"
          tasks:
            - name: "hello-world"
```

Related: #67
