### ISSUE TITLE
Suggested Services

### ISSUE THREAD

**Issue by agardnerIT** [keptn/enhancement-proposals#85]
# Suggested Services

Suggest services in the bridge that a user may wish to use with Keptn.

## Motivation

* Easier onboarding

## Explanation

A user creates a project via the bridge. They upload their shipyard. The bridge parses the tasks from the shipyard and then (new functionality) asks the user which tooling they wish to use to action those tasks.

Imagine the following tasks are parsed:

```
stages:
  - dev
  tasks:
    - deploy
    - test
    - evaluation
    - release
  - prod
  tasks:
    - deploy
    - release
    - evaluation
```

The user would be asked: "which tool would you like to action the `deploy` task in `dev`?

The user is then directed to the artifacthub installation instructions (or perhaps we can auto-install the service?)

We could offer links to "don't see your tool? Integrate anything" which links either to docs on the keptn/integrations repo`.

## Internal details

The task suggestions could be pulled from some field in artifacthub.

## Benefits

Such an integration would bring two benefits:

1) Much simpler onboarding process
2) A clear understanding to the user that tools action tasks and they are in control of which tools action which tasks.
3) As Keptn developers we can code in stats gathering to see which integrations, tools and use cases are popular and thus direct more effort to maintaining those.
